
[build]
  command = "npm run build"
  publish = "client/dist"
  functions = "serverless_functions/"  # Only needed if using serverless functions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200